# Generated by Django 5.0.6 on 2024-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_chatbottrace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='name',
        ),
        migrations.RemoveField(
            model_name='administrateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='administrateurprincipal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='administrateurprincipal',
            name='password',
        ),
        migrations.AddField(
            model_name='administrateur',
            name='mot_de_passe',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='nom',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='prenom',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AddField(
            model_name='administrateurprincipal',
            name='mot_de_passe',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AddField(
            model_name='administrateurprincipal',
            name='nom',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AddField(
            model_name='administrateurprincipal',
            name='prenom',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='email',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrateurprincipal',
            name='email',
            field=models.CharField(default='valeur_par_defaut', max_length=255),
        ),
        migrations.AlterField(
            model_name='administrateurprincipal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
