# Generated by Django 5.0.6 on 2024-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_administrateur_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('action', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotTrace',
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
